apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: default
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: frontend
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    nodePort: {{ .Values.frontend.service.nodePort }}