apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
  namespace: default
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: redis
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}